BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "company" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"grant_type"	TEXT NOT NULL,
	"client_secret"	TEXT NOT NULL,
	"client_id"	TEXT NOT NULL,
	"scope"	TEXT NOT NULL,
	"token"	TEXT
);
CREATE TABLE IF NOT EXISTS "product" (
	"id1"	INTEGER NOT NULL UNIQUE,
	"id2"	INTEGER NOT NULL UNIQUE,
	"company1_id"	INTEGER NOT NULL,
	"company2_id"	INTEGER NOT NULL,
	PRIMARY KEY("id1","id2")
);


CREATE TABLE IF NOT EXISTS "transactions" (
	"id" INTEGER PRIMARY KEY,
	"supplier"	VARCHAR(20) NOT NULL,
	"productID"	INTEGER NOT NULL,
	"quantity"	INTEGER NOT NULL,
	"total"	INTEGER NOT NULL,
	"datetime" DATETIME NOT NULL
);

COMMIT;